spring:
  config:
    import:
      configserver:http://localhost:8888
  application:
    name: aggregator
  cloud:
    config:
      retry:
        use-random-policy: true
        max-interval: 6000
      fail-fast: true
