spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer-db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "analyzer"
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
