server:
  port: 0
spring:
  datasource:
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/commerce_db
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

