spring:
  application:
    name: shopping-store
  config:
    import:
      configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      retry:
        use-random-policy: true
        max-interval: 6000
      fail-fast: true
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
